    #INCLUDE <P16F84A.INC>
    __CONFIG _XT_OSC&_WDT_OFF&_PWRTE_ON&_CP_OFF
	
	#DEFINE OUTPUT_LED PORTA,3
	
	#DEFINE PST_LCK    PORTA,0		;switch this to an internal memory address later
	#DEFINE PST_OPN	   PORTA,1		;switch this to an internal memory address later
	
	#DEFINE BT_OPN_CLS PORTB,7
	
	#DEFINE MATRIX_1   PORTB,6
	#DEFINE MATRIX_2   PORTB,5
	#DEFINE MATRIX_3   PORTB,4
	#DEFINE MATRIX_A   PORTB,3
	#DEFINE MATRIX_B   PORTB,2
	#DEFINE MATRIX_C   PORTB,1
	#DEFINE MATRIX_D   PORTB,0

; Counter setup
	ORG	0x00
	GOTO	SETUP

; Interrupt routine
	ORG 	0x04				;Start of interrupt routine
	BTFSC	INTCON,0			;check which interruption happened (RBIF here)
	GOTO 	BT_INT_CHECK
	GOTO	INTR_EXIT
BT_INT_CHECK				
	BTFSS	BT_OPN_CLS
	GOTO 	STATE_CHANGE_0
	GOTO	BT_INT_CHECK
	
STATE_CHANGE_0
	BTFSC	PST_LCK				;Check the previous state
	GOTO	STATE_CHANGE_PST_LCK
	BTFSC	PST_OPN
	GOTO	STATE_CHANGE_PST_OPN

STATE_CHANGE_PST_LCK				
	BTFSS	BT_OPN_CLS
	GOTO 	LCK
	GOTO	STATE_CHANGE_PST_LCK				

STATE_CHANGE_PST_OPN		
	BTFSS	BT_OPN_CLS
	GOTO 	OPN
	GOTO	STATE_CHANGE_PST_OPN

LCK
	;BCF	MATRIX_A
	;BCF	MATRIX_B
	;BCF	MATRIX_C
	;BCF	MATRIX_D
	
	BSF	PST_LCK
	BCF	PST_OPN
	BSF	OUTPUT_LED
	
	BSF	MATRIX_A
	BCF	MATRIX_B
	BCF	MATRIX_C
	BCF	MATRIX_D
	BTFSC	MATRIX_1
	GOTO	CORRECT_1
	BTFSC	MATRIX_2
	GOTO	WRONG_1
	BTFSC	MATRIX_3
	GOTO	WRONG_1
	
	BCF	MATRIX_A
	BSF	MATRIX_B
	BCF	MATRIX_C
	BCF	MATRIX_D
	BTFSC	MATRIX_1
	GOTO	WRONG_1
	BTFSC	MATRIX_2
	GOTO	WRONG_1
	BTFSC	MATRIX_3
	GOTO	WRONG_1
	
	BCF	MATRIX_A
	BCF	MATRIX_B
	BSF	MATRIX_C
	BCF	MATRIX_D
	BTFSC	MATRIX_1
	GOTO	WRONG_1
	BTFSC	MATRIX_2
	GOTO	WRONG_1
	BTFSC	MATRIX_3
	GOTO	WRONG_1
	
	BCF	MATRIX_A
	BCF	MATRIX_B
	BCF	MATRIX_C
	BSF	MATRIX_D
	BTFSC	MATRIX_1
	GOTO	WRONG_1
	BTFSC	MATRIX_2
	GOTO	WRONG_1
	BTFSC	MATRIX_3
	GOTO	WRONG_1
	
	GOTO	LCK

WRONG_1
BT_RLS_CHK_1_1		
	BTFSS	MATRIX_1
	GOTO 	BT_RLS_CHK_1_2
	GOTO	BT_RLS_CHK_1_1
BT_RLS_CHK_1_2		
	BTFSS	MATRIX_2
	GOTO 	BT_RLS_CHK_1_3
	GOTO	BT_RLS_CHK_1_2
BT_RLS_CHK_1_3		
	BTFSS	MATRIX_3
	GOTO 	WRONG_1_CNT
	GOTO	BT_RLS_CHK_1_3
	
	
WRONG_1_CNT
	BCF	MATRIX_A
	BCF	MATRIX_B
	BCF	MATRIX_C
	BCF	MATRIX_D
	
	BSF	MATRIX_A
	BCF	MATRIX_B
	BCF	MATRIX_C
	BCF	MATRIX_D
	BTFSC	MATRIX_1
	GOTO	WRONG_2
	BTFSC	MATRIX_2
	GOTO	WRONG_2
	BTFSC	MATRIX_3
	GOTO	WRONG_2
	
	BCF	MATRIX_A
	BSF	MATRIX_B
	BCF	MATRIX_C
	BCF	MATRIX_D
	BTFSC	MATRIX_1
	GOTO	WRONG_2
	BTFSC	MATRIX_2
	GOTO	WRONG_2
	BTFSC	MATRIX_3
	GOTO	WRONG_2
	
	BCF	MATRIX_A
	BCF	MATRIX_B
	BSF	MATRIX_C
	BCF	MATRIX_D
	BTFSC	MATRIX_1
	GOTO	WRONG_2
	BTFSC	MATRIX_2
	GOTO	WRONG_2
	BTFSC	MATRIX_3
	GOTO	WRONG_2
	
	BCF	MATRIX_A
	BCF	MATRIX_B
	BCF	MATRIX_C
	BSF	MATRIX_D
	BTFSC	MATRIX_1
	GOTO	WRONG_2
	BTFSC	MATRIX_2
	GOTO	WRONG_2
	BTFSC	MATRIX_3
	GOTO	WRONG_2
	
	GOTO	WRONG_1_CNT
	
WRONG_2
BT_RLS_CHK_2_1		
	BTFSS	MATRIX_1
	GOTO 	BT_RLS_CHK_2_2
	GOTO	BT_RLS_CHK_2_1
BT_RLS_CHK_2_2		
	BTFSS	MATRIX_2
	GOTO 	BT_RLS_CHK_2_3
	GOTO	BT_RLS_CHK_2_2
BT_RLS_CHK_2_3		
	BTFSS	MATRIX_3
	GOTO 	WRONG_2_CNT
	GOTO	BT_RLS_CHK_2_3

	
WRONG_2_CNT
	;BCF	MATRIX_A
	;BCF	MATRIX_B
	;BCF	MATRIX_C
	;BCF	MATRIX_D
	
	BSF	MATRIX_A
	BCF	MATRIX_B
	BCF	MATRIX_C
	BCF	MATRIX_D
	BTFSC	MATRIX_1
	GOTO	WRONG_3
	BTFSC	MATRIX_2
	GOTO	WRONG_3
	BTFSC	MATRIX_3
	GOTO	WRONG_3
	
	BCF	MATRIX_A
	BSF	MATRIX_B
	BCF	MATRIX_C
	BCF	MATRIX_D
	BTFSC	MATRIX_1
	GOTO	WRONG_3
	BTFSC	MATRIX_2
	GOTO	WRONG_3
	BTFSC	MATRIX_3
	GOTO	WRONG_3
	
	BCF	MATRIX_A
	BCF	MATRIX_B
	BSF	MATRIX_C
	BCF	MATRIX_D
	BTFSC	MATRIX_1
	GOTO	WRONG_3
	BTFSC	MATRIX_2
	GOTO	WRONG_3
	BTFSC	MATRIX_3
	GOTO	WRONG_3
	
	BCF	MATRIX_A
	BCF	MATRIX_B
	BCF	MATRIX_C
	BSF	MATRIX_D
	BTFSC	MATRIX_1
	GOTO	WRONG_3
	BTFSC	MATRIX_2
	GOTO	WRONG_3
	BTFSC	MATRIX_3
	GOTO	WRONG_3
	
	GOTO	WRONG_2_CNT
	
	
WRONG_3
BT_RLS_CHK_3_1		
	BTFSS	MATRIX_1
	GOTO 	BT_RLS_CHK_3_2
	GOTO	BT_RLS_CHK_3_1
BT_RLS_CHK_3_2		
	BTFSS	MATRIX_2
	GOTO 	BT_RLS_CHK_3_3
	GOTO	BT_RLS_CHK_3_2
BT_RLS_CHK_3_3		
	BTFSS	MATRIX_3
	GOTO 	WRONG_3_CNT
	GOTO	BT_RLS_CHK_3_3
	
	
WRONG_3_CNT	
	;BCF	MATRIX_A
	;BCF	MATRIX_B
	;BCF	MATRIX_C
	;BCF	MATRIX_D
	
	BSF	MATRIX_A
	BCF	MATRIX_B
	BCF	MATRIX_C
	BCF	MATRIX_D
	BTFSC	MATRIX_1
	GOTO	WRONG_4
	BTFSC	MATRIX_2
	GOTO	WRONG_4
	BTFSC	MATRIX_3
	GOTO	WRONG_4
	
	BCF	MATRIX_A
	BSF	MATRIX_B
	BCF	MATRIX_C
	BCF	MATRIX_D
	BTFSC	MATRIX_1
	GOTO	WRONG_4
	BTFSC	MATRIX_2
	GOTO	WRONG_4
	BTFSC	MATRIX_3
	GOTO	WRONG_4
	
	BCF	MATRIX_A
	BCF	MATRIX_B
	BSF	MATRIX_C
	BCF	MATRIX_D
	BTFSC	MATRIX_1
	GOTO	WRONG_4
	BTFSC	MATRIX_2
	GOTO	WRONG_4
	BTFSC	MATRIX_3
	GOTO	WRONG_4
	
	BCF	MATRIX_A
	BCF	MATRIX_B
	BCF	MATRIX_C
	BSF	MATRIX_D
	BTFSC	MATRIX_1
	GOTO	WRONG_4
	BTFSC	MATRIX_2
	GOTO	WRONG_4
	BTFSC	MATRIX_3
	GOTO	WRONG_4
	
	GOTO	WRONG_3_CNT
	
	
WRONG_4
BT_RLS_CHK_4_1		
	BTFSS	MATRIX_1
	GOTO 	BT_RLS_CHK_4_2
	GOTO	BT_RLS_CHK_4_1
BT_RLS_CHK_4_2		
	BTFSS	MATRIX_2
	GOTO 	BT_RLS_CHK_4_3
	GOTO	BT_RLS_CHK_4_2
BT_RLS_CHK_4_3		
	BTFSS	MATRIX_3
	GOTO 	WRONG_4_CNT
	GOTO	BT_RLS_CHK_4_3
	
WRONG_4_CNT	
	BCF	MATRIX_A
	BCF	MATRIX_B
	BCF	MATRIX_C
	BCF	MATRIX_D
	
	BSF	PST_LCK
	BCF	PST_OPN
	BSF	OUTPUT_LED
	
	GOTO	INTR_EXIT
	
CORRECT_1
BT_RLS_CHK_CR_1_1		
	BTFSS	MATRIX_1
	GOTO 	BT_RLS_CHK_CR_1_2
	GOTO	BT_RLS_CHK_CR_1_1
BT_RLS_CHK_CR_1_2		
	BTFSS	MATRIX_2
	GOTO 	BT_RLS_CHK_CR_1_3
	GOTO	BT_RLS_CHK_CR_1_2
BT_RLS_CHK_CR_1_3		
	BTFSS	MATRIX_3
	GOTO 	CORRECT_1_CNT
	GOTO	BT_RLS_CHK_CR_1_3	
	
CORRECT_1_CNT	
	;BCF	MATRIX_A
	;BCF	MATRIX_B
	;BCF	MATRIX_C
	;BCF	MATRIX_D
	
	BSF	MATRIX_A
	BCF	MATRIX_B
	BCF	MATRIX_C
	BCF	MATRIX_D
	BTFSC	MATRIX_1
	GOTO	WRONG_2
	BTFSC	MATRIX_2
	GOTO	CORRECT_2
	BTFSC	MATRIX_3
	GOTO	WRONG_2
	
	BCF	MATRIX_A
	BSF	MATRIX_B
	BCF	MATRIX_C
	BCF	MATRIX_D
	BTFSC	MATRIX_1
	GOTO	WRONG_2
	BTFSC	MATRIX_2
	GOTO	WRONG_2
	BTFSC	MATRIX_3
	GOTO	WRONG_2
	
	BCF	MATRIX_A
	BCF	MATRIX_B
	BSF	MATRIX_C
	BCF	MATRIX_D
	BTFSC	MATRIX_1
	GOTO	WRONG_2
	BTFSC	MATRIX_2
	GOTO	WRONG_2
	BTFSC	MATRIX_3
	GOTO	WRONG_2
	
	BCF	MATRIX_A
	BCF	MATRIX_B
	BCF	MATRIX_C
	BSF	MATRIX_D
	BTFSC	MATRIX_1
	GOTO	WRONG_2
	BTFSC	MATRIX_2
	GOTO	WRONG_2
	BTFSC	MATRIX_3
	GOTO	WRONG_2
	
	GOTO	CORRECT_1
	
CORRECT_2
BT_RLS_CHK_CR_2_1		
	BTFSS	MATRIX_1
	GOTO 	BT_RLS_CHK_CR_2_2
	GOTO	BT_RLS_CHK_CR_2_1
BT_RLS_CHK_CR_2_2		
	BTFSS	MATRIX_2
	GOTO 	BT_RLS_CHK_CR_2_3
	GOTO	BT_RLS_CHK_CR_2_2
BT_RLS_CHK_CR_2_3		
	BTFSS	MATRIX_3
	GOTO 	CORRECT_2_CNT
	GOTO	BT_RLS_CHK_CR_2_3	
	
CORRECT_2_CNT	
	;BCF	MATRIX_A
	;BCF	MATRIX_B
	;BCF	MATRIX_C
	;BCF	MATRIX_D
	
	BSF	MATRIX_A
	BCF	MATRIX_B
	BCF	MATRIX_C
	BCF	MATRIX_D
	BTFSC	MATRIX_1
	GOTO	WRONG_3
	BTFSC	MATRIX_2
	GOTO	WRONG_3
	BTFSC	MATRIX_3
	GOTO	CORRECT_3
	
	BCF	MATRIX_A
	BSF	MATRIX_B
	BCF	MATRIX_C
	BCF	MATRIX_D
	BTFSC	MATRIX_1
	GOTO	WRONG_3
	BTFSC	MATRIX_2
	GOTO	WRONG_3
	BTFSC	MATRIX_3
	GOTO	WRONG_3
	
	BCF	MATRIX_A
	BCF	MATRIX_B
	BSF	MATRIX_C
	BCF	MATRIX_D
	BTFSC	MATRIX_1
	GOTO	WRONG_3
	BTFSC	MATRIX_2
	GOTO	WRONG_3
	BTFSC	MATRIX_3
	GOTO	WRONG_3
	
	BCF	MATRIX_A
	BCF	MATRIX_B
	BCF	MATRIX_C
	BSF	MATRIX_D
	BTFSC	MATRIX_1
	GOTO	WRONG_3
	BTFSC	MATRIX_2
	GOTO	WRONG_3
	BTFSC	MATRIX_3
	GOTO	WRONG_3
	
	GOTO	CORRECT_2
	
	
CORRECT_3
BT_RLS_CHK_CR_3_1		
	BTFSS	MATRIX_1
	GOTO 	BT_RLS_CHK_CR_3_2
	GOTO	BT_RLS_CHK_CR_3_1
BT_RLS_CHK_CR_3_2		
	BTFSS	MATRIX_2
	GOTO 	BT_RLS_CHK_CR_3_3
	GOTO	BT_RLS_CHK_CR_3_2
BT_RLS_CHK_CR_3_3		
	BTFSS	MATRIX_3
	GOTO 	CORRECT_3_CNT
	GOTO	BT_RLS_CHK_CR_3_3	
	
CORRECT_3_CNT	
	;BCF	MATRIX_A
	;BCF	MATRIX_B
	;BCF	MATRIX_C
	;BCF	MATRIX_D
	
	BSF	MATRIX_A
	BCF	MATRIX_B
	BCF	MATRIX_C
	BCF	MATRIX_D
	BTFSC	MATRIX_1
	GOTO	WRONG_4
	BTFSC	MATRIX_2
	GOTO	WRONG_4
	BTFSC	MATRIX_3
	GOTO	WRONG_4
	
	BCF	MATRIX_A
	BSF	MATRIX_B
	BCF	MATRIX_C
	BCF	MATRIX_D
	BTFSC	MATRIX_1
	GOTO	CORRECT_4
	BTFSC	MATRIX_2
	GOTO	WRONG_4
	BTFSC	MATRIX_3
	GOTO	WRONG_4
	
	BCF	MATRIX_A
	BCF	MATRIX_B
	BSF	MATRIX_C
	BCF	MATRIX_D
	BTFSC	MATRIX_1
	GOTO	WRONG_4
	BTFSC	MATRIX_2
	GOTO	WRONG_4
	BTFSC	MATRIX_3
	GOTO	WRONG_4
	
	BCF	MATRIX_A
	BCF	MATRIX_B
	BCF	MATRIX_C
	BSF	MATRIX_D
	BTFSC	MATRIX_1
	GOTO	WRONG_4
	BTFSC	MATRIX_2
	GOTO	WRONG_4
	BTFSC	MATRIX_3
	GOTO	WRONG_4
	
	GOTO	CORRECT_3
	
	
CORRECT_4
BT_RLS_CHK_CR_4_1		
	BTFSS	MATRIX_1
	GOTO 	BT_RLS_CHK_CR_4_2
	GOTO	BT_RLS_CHK_CR_4_1
BT_RLS_CHK_CR_4_2		
	BTFSS	MATRIX_2
	GOTO 	BT_RLS_CHK_CR_4_3
	GOTO	BT_RLS_CHK_CR_4_2
BT_RLS_CHK_CR_4_3		
	BTFSS	MATRIX_3
	GOTO 	CORRECT_4_CNT
	GOTO	BT_RLS_CHK_CR_4_3	
	
CORRECT_4_CNT	
	BCF	MATRIX_A
	BCF	MATRIX_B
	BCF	MATRIX_C
	BCF	MATRIX_D
	
	BCF	PST_LCK
	BSF	PST_OPN
	BCF	OUTPUT_LED
	
	GOTO	INTR_EXIT
	

OPN	
	BSF	PST_LCK
	BCF	PST_OPN
	BSF	OUTPUT_LED

	GOTO	INTR_EXIT

INTR_EXIT
	BCF	INTCON,0			;The interrupt flags must be cleared 
	RETFIE

SETUP
; Port configuration
	
	BSF     STATUS,5		  	;Switch to Bank 1               
	MOVLW   b'11110000'		  	;Set Port B pins to input/output
	MOVWF   TRISB
	MOVLW	b'00000'
	MOVWF	TRISA
	
	;MOVLW 	b'10000111';			;prescaler on (1:256), pull-up off
	;MOVWF	OPTION_REG
	MOVLW	b'10001000';			;interrupt enable bits (global, RB7:RB4)
	MOVWF	INTCON;				
	
	BCF     STATUS,5			;Switch to Bank 0
	
	BCF	MATRIX_A
	BCF	MATRIX_B
	BCF	MATRIX_C
	BCF	MATRIX_D
	
	BSF	OUTPUT_LED
	
	BSF	PST_LCK
	BCF	PST_OPN

	BCF	PORTA,2
	BCF	PORTA,4
	
	GOTO	START
START
	GOTO	START
	END